name: Two Job Workflow

on: workflow_dispatch  # Manual trigger

jobs:

  print:
    runs-on: ubuntu-latest
    steps:
      - name: Job One
        run: echo "Hello, job one is done"

  math:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3
        #with:
         # token: ${{ secrets.PAT_TOKEN }}   # PAT stored as secret
          #persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3️⃣ Run Python script
      - name: Run Python file
        run: |
          python addition.py

      # 4️⃣ Commit and push output.txt
      - name: Commit and push output.txt
        run: |
          git config --local user.email "barathwaj2033@gmail.com"
          git config --local user.name "Vicky-karthik-2003"
          git add output.txt
          git commit -m "Add output.txt from workflow" || echo "No changes to commit"
          git push origin develop
